#!/bin/bash
sudo find /mass/vafsb/imcap -name "c*.jpg"  -delete
sudo find /mass/vafsb/imcap/pyOutput -name "*.txt"  -delete
sudo find /mass/vafsb/imcap/output_redaction -name "*.csv"  -delete
sudo find /mass/vafsb/imcap/output_redaction/boxplots/ -name "*.jpg"  -delete
sudo find /mass/vafsb/imcap/output_redaction/redacted/ -name "*.jpg"  -delete
sudo find /mass/vafsb/imcap/output_redaction/cropped/ -name "*.jpg"  -delete
